
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from ctypes import windll  
import pyglet, os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")

pyglet.font.add_file('fonts/Inter-VariableFont_slnt,wght.ttf')
windll.shcore.SetProcessDpiAwareness(1)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("960x540")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 540,
    width = 960,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    480.0,
    540.0,
    fill="#C7D3DD",
    outline="")

canvas.create_rectangle(
    480.0,
    0.0,
    960.0,
    540.0,
    fill="#E7ECEF",
    outline="")

canvas.create_text(
    583.0,
    66.0,
    anchor="nw",
    text="______________________________________",
    fill="#000000",
    font=("Inter Light", 16 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    625.4709320068359,
    255.68053436279297,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=533.0,
    y=228.0,
    width=184.94186401367188,
    height=53.36106872558594
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=771.0,
    y=227.0,
    width=135.04006958007812,
    height=55.36106872558594
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=668.0,
    y=383.0,
    width=103.0,
    height=44.45420837402344
)

canvas.create_text(
    555.0,
    115.0,
    anchor="nw",
    text="Press Browse and select your FDH Excel file ",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    160.0,
    74.0,
    anchor="nw",
    text="Forage Data Hub",
    fill="#000000",
    font=("Inter Regular", 20 * -1)
)

canvas.create_text(
    64.0,
    34.0,
    anchor="nw",
    text="Autopopulate Longitude and Latitude",
    fill="#000000",
    font=("Inter Regular", 20 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    241.0,
    227.0,
    image=image_image_1
)

canvas.create_text(
    56.0,
    382.0,
    anchor="nw",
    text="Note: City and state names must be spelled out entirely",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    56.0,
    399.0,
    anchor="nw",
    text="in order to find the appropriate longitude and latitude.",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    647.0,
    47.0,
    anchor="nw",
    text="Upload Excel File",
    fill="#000000",
    font=("Inter", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
